### ISSUE TITLE
Prepare Profiles of big networks

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#20]
@cpiponiot, and maybe also @gabrielareto,
 
Could you list here what networks have standardize data, a link to an example of their data and, if available, their metadata?

The idea is that the ShinyApp will auto-populate the inputs if the user says its data comes from one of those networks.  

- [ ] TmFO , ...
- [ ]
- [ ]

**Comment by cpiponiot** [comment]
Hi Valentine, sorry for the delay, I'm just seeing this. TmFO doesn't have a standardized format. You can find examples of networks that (I think) do have a standardized format [here](https://www.dropbox.com/home/ITFSA-data-federation/data-samples), including CTFS-ForestGEO , SEOSAW, ATDN, TreeCo.
