### ISSUE TITLE
Merge several tables

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#24]
- [x]  ask the user which columns they want to merge
- [x] Identify columns (names, units, format)
- [x] rename and format columns (in the same way for common columns between tables)
- [x] from wide format to long format 
- [ ] ask the key and merge by it (idtree, year, measure_id)
- [ ] produce a data dictionary (1 diff/table or only for the output table?)
- [ ] Alert the user in case of error, telling him to handle it on his side before using this table

**Comment by ValentineHerr** [comment]
@VincyaneBadouard je crois qu'on peut fermer ca, l'application va merger comme l'utilisateur veut et ensuite, il me semble que tu as tes fonctions qui feront la detection d'erreurs, de duplicates etc... non? Si tu es d'accord tu peux fermer cette issue.
