### ISSUE TITLE
export to a predetermined Profile

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#28]
the ReversedRequiredFormat function should:

- [x] reverse Date format
- [x] get circ if needed
- [x] reverse to output profile units:
  - [x]  DBH
  - [x] Circ
  - [x] POM
  - [x] Height
  - [x] PlotArea
  - [x] SubPlotArea
- [ ] ~~potentially adjust DBH to the standard POM of the output Profile?~~
- [ ] ~~combine/separate scientific name~~
- [x] reverse column names
- [ ] untidy (DONE BUT NEED TO ASK USER IN APP)

things that can't be converted to output Profile:
- it is not possible to go from alive status TRUE/FALSE back to the various codes a network may have
- same with commercial status

**Comment by VincyaneBadouard** [comment]
- DBH correction is/will be done at the user's default POM
It is not possible to put everyone's data in the same POM

- the Genus and Species columns that generate ScientificName have not been removed
/the ScientificName column that generates Genus and Species has not been removed

- untidy : user choice

- for the code columns, the original column should not be deleted, and all the computed columns stay

**Comment by ValentineHerr** [comment]
Closing this.
I am not going to try "untidying" and "unmerging" the data until someone specifically asks for it.
