### ISSUE TITLE
rdsPermanentPlots

### ISSUE THREAD

**Issue by gabrielareto** [VincyaneBadouard/TreeData#3]
https://github.com/marbotte/sibPlot
The first release is expected to happen on 28-December-2021.

Marius Bottin is working with colleagues in Colombia on something similar. Worth checking that repository. 

message from Roy, for the record: estamos trabajando en algo "similar" pero bajo el concepto de servicio de datos relacionales (.rds) –una estructura similar a la que manejan las diferentes iniciativas globlales– pero con lógica de código abierto. Estamos desarrollando un "R package" en Github, liderado por Marius, donde el código tenga la capacidad de consumir cualquier formato y estructura de entrada (dentro de nuestro universo muestreal), organizarlos en la .rds y migrarlos (hacerlos interoperables) a cualquier estructura, todo a partir de funciones independientes. Chévere charlarlo para ver donde convergemos.

**Comment by ValentineHerr** [comment]
@gabrielareto any follow up with this?
