### ISSUE TITLE
ToDo list for StatusCorrection()

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#49]
- **Tests:**

- [x] check that the fct does not add a new row when *AddRowsForForgottenCensuses* = FALSE

**Comment by ValentineHerr** [comment]
@cpiponiot FYI, I have been revamping this function (using regex) to make it faster. I am not ready yet, but I wanted to let you know so you don't spend time on it.

**Comment by ValentineHerr** [comment]
- [ ] I am ignoring "RemoveRBeforeAlive" and "RemoveRAfterDeath" for now but we may want to add it back if we think it is necessary
