### ISSUE TITLE
FullErrorProcessiong question(s)

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#60]
Hi @VincyaneBadouard,

In your function `FullErrorProcessing`, the options for argument `WhatToCorrect` are `c("taper", "POM change", "punctual", "shift")` (see this [line](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/FullErrorProcessing.R#L75)) but in your code you do not allow `taper` (see this [line](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/FullErrorProcessing.R#L168))

Which of the two is correct?

**Comment by VincyaneBadouard** [comment]
Hi!

you can add "taper" to the line where it is missing

Sorry for the typo

**Comment by ValentineHerr** [comment]
@VincyaneBadouard, what happens if someone selects both `taper` and `POM change`?

**Comment by ValentineHerr** [comment]
General question for your @VincyaneBadouard, where can we tell if the arguments can be a multiple choice?

**Comment by ValentineHerr** [comment]
@VincyaneBadouard the list of possible arguments [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L140) does not match the one [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L195), which one is the correct one?

**Comment by ValentineHerr** [comment]
> @VincyaneBadouard the list of possible arguments [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L140) does not match the one [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L195), which one is the correct one?

I think the correct is `c("quadratic", "linear", "individual", "phylogenetic hierarchical")` and I believe the user can select more than one. @VincyaneBadouard, please correct me if I am wrong

**Comment by VincyaneBadouard** [comment]
> @VincyaneBadouard, what happens if someone selects both `taper` and `POM change`?
There will be the transformation of the diameters into a diameter equivalent to 1.30m (default value),
then it will consider the initial POM and when there is a change of this initial POM it will make either an individual correction by weighted average of the diameter values that have been corrected by the taper, or a hierarchical phylogenetic correction (average of the growths of the species/genus/family, stand).

**Comment by VincyaneBadouard** [comment]
> General question for your @VincyaneBadouard, where can we tell if the arguments can be a multiple choice?
> 
> (I think I manually indicated if it was a multiple choice, but I can't remember how I knew)

I'm not sur to understand your question. You tell it in the doc and in the check argument in the stop message. But it seems to me that you once found a function that automatically sends a message according to your criteria

**Comment by VincyaneBadouard** [comment]
> > @VincyaneBadouard the list of possible arguments [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L140) does not match the one [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L195), which one is the correct one?
> 
> I think the correct is `c("quadratic", "linear", "individual", "phylogenetic hierarchical")` and I believe the user can select more than one. @VincyaneBadouard, please correct me if I am wrong

Yes sorry, it is not consistent. in fact after many modifications on the diametric correction methods, the quadratic regression is no longer possible because only 2 values are taken to make the regression (Local = TRUE).
So there is no need to specify "linear" or "quadratic" in the current methods.
On the other hand, indicating "individual" or "phylophylogenetic hierarchical" is essential, and if both are set, "individual" will be considered and the individual correction will be applied.

**Comment by ValentineHerr** [comment]
> > > @VincyaneBadouard the list of possible arguments [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L140) does not match the one [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L195), which one is the correct one?
> > 
> > 
> > I think the correct is `c("quadratic", "linear", "individual", "phylogenetic hierarchical")` and I believe the user can select more than one. @VincyaneBadouard, please correct me if I am wrong
> 
> Yes sorry, it is not consistent. in fact after many modifications on the diametric correction methods, the quadratic regression is no longer possible because only 2 values are taken to make the regression (Local = TRUE). So there is no need to specify "linear" or "quadratic" in the current methods. On the other hand, indicating "individual" or "phylophylogenetic hierarchical" is essential, and if both are set, "individual" will be considered and the individual correction will be applied.

Thanks for your answer. So I should remove "linear" in the [example ](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L121)of DiameterCorrections, correct?

**Comment by ValentineHerr** [comment]
> > General question for your @VincyaneBadouard, where can we tell if the arguments can be a multiple choice?
> > (I think I manually indicated if it was a multiple choice, but I can't remember how I knew)
> 
> I'm not sur to understand your question. You tell it in the doc and in the check argument in the stop message. But it seems to me that you once found a function that automatically sends a message according to your criteria

I meant if there was a clear indication somewhere (presumably in the doc), that the user can select multiplie options for one argument, for example run the function with `WhatToCorrect = c("taper", "POM change", "punctual")` or even `WhatToCorrect =  c("taper", "POM change", "punctual", "shift")`, as oppose to only be allowed to pick one and only one of the options, like  `WhatToCorrect =  "taper"` or  `WhatToCorrect =  "shift"`
I couldn't find a place in the doc that would specify that. (I have the same with `CorrectionType`)

**Comment by ValentineHerr** [comment]
> Hi!
> 
> you can add "taper" to the line where it is missing
> 
> Sorry for the typo

@VincyaneBadouard I think I then also need to add a description for the option "taper" [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L48-L53).  Would this be okay:

' @param WhatToCorrect Possible values: **_"taper"_**, "POM change", "punctual", "shift"
#'   (character)
**_#' "taper"; transform the tree diameter measured at a given height into the diameter corresponding to the default measurement height (argument DefaultHOM), using an allometry (argument TaperFormula)._**
#'   - "POM change": detect POM change in the column `POM` and correct the
#'                   Diameter values from it.
#'   - "punctual": detect if the error is punctual and correct it by
#'                 interpolation.
#'   - "shift": detect if there is a shift of several Diameter values and
#'              links them to the 1st measurements set.

**Comment by VincyaneBadouard** [comment]
> > Hi!
> > you can add "taper" to the line where it is missing
> > Sorry for the typo
> 
> @VincyaneBadouard I think I then also need to add a description for the option "taper" [here](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L48-L53). Would this be okay:
> 
> ' @param WhatToCorrect Possible values: **_"taper"_**, "POM change", "punctual", "shift" #' (character) **_#' "taper"; transform the tree diameter measured at a given height into the diameter corresponding to the default measurement height (argument DefaultHOM), using an allometry (argument TaperFormula)._** #' - "POM change": detect POM change in the column `POM` and correct the #' Diameter values from it. #' - "punctual": detect if the error is punctual and correct it by #' interpolation. #' - "shift": detect if there is a shift of several Diameter values and #' links them to the 1st measurements set.

hmm no because it is not the DiameterCorrection function that does the taper correction. So only in the FullErrorProcessing function "taper" is accepted in the WhatToCorrect  argument.

**Comment by VincyaneBadouard** [comment]
> > > General question for your @VincyaneBadouard, where can we tell if the arguments can be a multiple choice?
> > > (I think I manually indicated if it was a multiple choice, but I can't remember how I knew)
> > 
> > 
> > I'm not sur to understand your question. You tell it in the doc and in the check argument in the stop message. But it seems to me that you once found a function that automatically sends a message according to your criteria
> 
> I meant if there was a clear indication somewhere (presumably in the doc), that the user can select multiplie options for one argument, for example run the function with `WhatToCorrect = c("taper", "POM change", "punctual")` or even `WhatToCorrect = c("taper", "POM change", "punctual", "shift")`, as oppose to only be allowed to pick one and only one of the options, like `WhatToCorrect = "taper"` or `WhatToCorrect = "shift"` I couldn't find a place in the doc that would specify that. (I have the same with `CorrectionType`)

I specify unless forgotten (which can be many) if only 1 value is accepted as here: https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/DiameterCorrection.R#L26

**Comment by VincyaneBadouard** [comment]
Super, thank you for your checks!
Have users tried the corrections?

**Comment by ValentineHerr** [comment]
no not yet, some of those issues (like the "taper" issue) are breaking the app, so I need to put more work into this.

**Comment by ValentineHerr** [comment]
> hmm no because it is not the DiameterCorrection function that does the taper correction. So only in the FullErrorProcessing function "taper" is accepted in the WhatToCorrect argument.

I see now that `FullErrorProcessing` does not have the "taper" option in the help file because of `#' @inheritParams DiameterCorrection`

@VincyaneBadouard,  Do you have a suggestion on how to add that in that help file?

**Comment by VincyaneBadouard** [comment]
No, sorry I don't know. Maybe the answer is in: https://cran.r-project.org/web/packages/roxygen2/vignettes/reuse.html

**Comment by ValentineHerr** [comment]
> On the other hand, indicating "individual" or "phylophylogenetic hierarchical" is essential, and if both are set, "individual" will be considered and the individual correction will be applied.


This to me sounds like we should only allow one option, right?
So in the help file we should add the "1 value" you were refering too, correct?. 

````
#' @param CorrectionType Possible values: "individual", "phylogenetic
#'   hierarchical" (character, **1 value**).
```

**Comment by VincyaneBadouard** [comment]
> > On the other hand, indicating "individual" or "phylophylogenetic hierarchical" is essential, and if both are set, "individual" will be considered and the individual correction will be applied.
> 
> This to me sounds like we should only allow one option, right? So in the help file we should add the "1 value" you were refering too, correct?.
> 
> ```
> #' @param CorrectionType Possible values: "individual", "phylogenetic
> #'   hierarchical" (character, **1 value**).
> ```
> ```

absolutely

**Comment by VincyaneBadouard** [comment]
> If he does, each correction is performed one after the other?

yes
1) POM change
2) detection if it's a shift or a punctual error
3) put NA for the punctual error
4) correct the shifts errors
5) replace NAs by regression

**Comment by ValentineHerr** [comment]
> > If he does, each correction is performed one after the other?
> 
> yes
> 
> 1. POM change
> 2. detection if it's a shift or a punctual error
> 3. put NA for the punctual error
> 4. correct the shifts errors
> 5. replace NAs by regression

Ok... maybe I'll create a separate "taper" argument in the FullErrorProcessing function
