### ISSUE TITLE
self referencing issues in correction functions

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#61]
I believe [this line of code](https://github.com/VincyaneBadouard/TreeData/blob/3ff546d48ec47a022b7b66c924560b70cb4603e6/R/PhylogeneticHierarchicalCorrection.R#L332) causes this warning:

```
Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can 
add this new column by reference. At an earlier point, this data.table has been copied by R 
(or was created manually using structure() or similar). Avoid names<- and attr<- which in R 
currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, 
?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue 
tracker so the root cause can be fixed or this message improved.
```

I believe @cpiponiot you had fixed this issue in some other functions. I'll try to fix this.

**Comment by cpiponiot** [comment]
Yes, I think that's the problem too, but I haven't found a good way to deal with it, so I just removed the warnings. I don't think it causes any big problems but I'm not sure. I think we could change the name of the DBHcor variable (to be different from the DataTree column) to avoid this problem.
