### ISSUE TITLE
user checklist

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#71]
Things to add in the checklist on first page of app:

- [x] make it more clear that you don't actually need to check the boxes for the app to work, this is just a guide for the user
- [x] if the user will merge, make sure he has the list of columns that are common betwen tables, so they all get checked as "KEYs" and there are no extra columns with a ".y" appended to them. That behavior is not a problem for the app, but it is not pretty
- [ ] ...

**Comment by gabrielareto** [comment]
The checklist could be part of the documentation that we will have to provide, perhaps a pdf to download. We do not need to do everything through shiny
