### ISSUE TITLE
unique IDs

### ISSUE THREAD

**Issue by gabrielareto** [VincyaneBadouard/TreeData#87]
This may be redundant, but I find within BotanicalCorrection a check of unique tree ids:

"identify the Idtree(s) having several P-SubP-TreeFieldNum combinations"

I feel the generation of unique IDs and a log of the problems or incongruences should happen earlier on the process, the individual correction functions should not "worry" about this again and again.

**Comment by ValentineHerr** [comment]
Agreed, and a check is happening earlier, so I think you can delete that part.
