### ISSUE TITLE
corrections require that all data owners in a project go through the app

### ISSUE THREAD

**Issue by gabrielareto** [VincyaneBadouard/TreeData#88]
corrections require that all data owners in a project go through the app. I realized this when thinking about taxonomic backbones but it applies to all corrections.

example: network A wants to share data with network B. Network A goes through the app and get accepted names. Although network B has their data in format B, they do not have their names checked, so there could be incongruencies there. Network B will have to go through the app at least to correct their names. 

the same applies to all corrections. For example, one should not compare AGB of plots that went through taper corrections with AGB of plots that did not go through taper corrections.

this is particularly important if we give multiple options to run the corrections. E.g. two taxonomic backbones or two tapering functions to assume. Those parameters will have to be part of the profiles, otherwise two networks will not be able to run the same corrections.

going back to previous conversations: [merging datasets] and [making corrections] may need to be two different steps, so users can merge their datasets into one, and then apply corrections on just one big dataset.

**Comment by ValentineHerr** [comment]
That is a good point and we need to communicate about this.

I'll need to add wording in the app
